<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Suppliers</name>
   <tag></tag>
   <elementGuidId>5617fb38-2f50-4ea5-b9b4-2e9363fbaac1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;ACCOUNTS&quot;)/li[2]/a[1][count(. | //a[@href = 'https://www.phptravels.net/admin/accounts/suppliers/' and (text() = 'Suppliers' or . = 'Suppliers')]) = count(//a[@href = 'https://www.phptravels.net/admin/accounts/suppliers/' and (text() = 'Suppliers' or . = 'Suppliers')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.phptravels.net/admin/accounts/suppliers/</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Suppliers</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ACCOUNTS&quot;)/li[2]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
