<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_Exclusion</name>
   <tag></tag>
   <elementGuidId>a501d4d4-05eb-46e3-8abb-19e46ba0b512</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id=&quot;EXCLUSIONS&quot;]//*[contains(text(),&quot;${exclude}&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
